export { default as Charts } from './charts'
export { default as Cryptos } from './cryptos'
export { default as Home } from './home'
export { default as NotFound } from './notFound'
export { default as Spread } from './spread'
export { default as Invest } from './invest'
