version: '3.8'
services:
  server:
    build: .
    image: node:16.15.0
    container_name: server
    working_dir: /app
    ports:
      - 3000:3000
    volumes:
      - .:/app
    command: yarn run start
