version: '3.8'
services:
  server:
    container_name: stocks-server
    image: node:16.15.0
    working_dir: /app
    ports:
      - "3000:3000"
    volumes:
      - ./.:/app
    command: yarn run dev
