name: Deploy
run-name: Deploying ${{ github.sha }}
on:  [push, pull_request]
jobs: 
  Deploy:
    env: 
      AWS_USER: ${{ secrets.AWS_USER }}
      AWS_KEY: ${{ secrets.AWS_KEY }}
      DEPLOYER_PEM: ${{ secrets.DEPLOYER_PEM }}
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: soccerKevin/Stocks
      - name: Configure AWS deployer credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::267135861046:role/GithubActionsDeployer
          aws-region: us-west-1

      - name: Launch instance
        run: aws ec2 run-instances --image-id ami-073e64e4c237c08ad --count 1 --instance-type t2.micro --security-group-ids sg-05d4593547be6e90d

      # - name: SSH into server
      #   run: ssh -i "stocksServer.pem" ec2-user@ec2-13-57-214-123.us-west-1.compute.amazonaws.com

      # - name: Install AWS_CLI
      #   run: sudo yum update -y
      #   run: sudo yum install docker -y
      #   run: sudo service docker start
      #   run: sudo usermod -a -G docker ec2-user


